baseURL: https://badoll.github.io/
languageCode: en-us
title: lvv3's cafÃ©
theme: PaperMod
enableEmoji: true
enableGitInfo: true
menu:
  main:
    - name: "Archive"
      weight: 10
      identifier: "archives"
      url: "/archives/"
    - name: "Category"
      weight: 20
      identifier: "categories"
      url: "/categories/"
    - name: "Tag"
      weight: 30
      identifier: "tags"
      url: "/tags/"

params:
  DateFormat: "2006-01-02"
  ShowToc: true # æ˜¾ç¤ºç›®å½•
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
  #ShowLastMod: true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´
  ShowReadingTime: true
  ShowWordCounts: true
  VisitCount: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # éšè—é¡µè„š
  defaultTheme: auto  # defaultTheme: light or  dark 
  disableThemeToggle: false
  homeInfoParams:
    Title: Hi ThereğŸ‘‹
    Content: The dots will somehow connect in the future
  socialIcons:
    - name: "github"
      url: "https://github.com/badoll"

taxonomies:
  category: categories
  tag: tags

markup:
    goldmark:
        renderer:
            unsafe: true # HUGO é»˜è®¤è½¬ä¹‰ Markdown æ–‡ä»¶ä¸­çš„ HTML ä»£ç ï¼Œå¦‚éœ€å¼€å¯çš„è¯
    highlight:
        # anchorLineNos: true
        codeFences: true  
        guessSyntax: true
        lineNos: true
        # noClasses: false
        # style: monokai
        style: darcula

        # codeFencesï¼šä»£ç å›´æ åŠŸèƒ½ï¼Œè¿™ä¸ªåŠŸèƒ½ä¸€èˆ¬éƒ½è¦è®¾ä¸º true çš„ï¼Œä¸ç„¶å¾ˆéš¾çœ‹ï¼Œå°±æ˜¯å¹²å·´å·´çš„-ä»£ç æ–‡å­—ï¼Œæ²¡æœ‰é¢œè‰²ã€‚
        # guessSyntaxï¼šçŒœæµ‹è¯­æ³•ï¼Œè¿™ä¸ªåŠŸèƒ½å»ºè®®è®¾ç½®ä¸º true, å¦‚æœä½ æ²¡æœ‰è®¾ç½®è¦æ˜¾ç¤ºçš„è¯­è¨€åˆ™ä¼šè‡ªåŠ¨åŒ¹é…ã€‚
        # hl_Linesï¼šé«˜äº®çš„è¡Œå·ï¼Œä¸€èˆ¬è¿™ä¸ªä¸è®¾ç½®ï¼Œå› ä¸ºæ¯ä¸ªä»£ç å—æˆ‘ä»¬å¯èƒ½å¸Œæœ›è®©é«˜äº®çš„åœ°æ–¹ä¸ä¸€æ ·ã€‚
        # lineNoStartï¼šè¡Œå·ä»ç¼–å·å‡ å¼€å§‹ï¼Œä¸€èˆ¬ä» 1 å¼€å§‹ã€‚
        # lineNosï¼šæ˜¯å¦æ˜¾ç¤ºè¡Œå·ï¼Œæˆ‘æ¯”è¾ƒå–œæ¬¢æ˜¾ç¤ºï¼Œæ‰€ä»¥æˆ‘è®¾ç½®çš„ä¸º true.
        # lineNumbersInTableï¼šä½¿ç”¨è¡¨æ¥æ ¼å¼åŒ–è¡Œå·å’Œä»£ç ,è€Œä¸æ˜¯ æ ‡ç­¾ã€‚è¿™ä¸ªå±æ€§ä¸€èˆ¬è®¾ç½®ä¸º true.
        # noClassesï¼šä½¿ç”¨ class æ ‡ç­¾ï¼Œè€Œä¸æ˜¯å†…åµŒçš„å†…è”æ ·å¼