baseURL: https://badoll.github.io/
languageCode: en-us
title: Nahuh's Blog
theme: PaperMod
params:
  homeInfoParams:
    Title: Hi thereğŸ‘‹ğŸ»
    Content: Exploring the Unknown Unknown

  socialIcons:
    - name: "github"
      url: "https://github.com/badoll"
